# Generated by Django 6.0.4 on 2026-05-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='Standard', max_length=20, verbose_name='Size'),
        ),
    ]
